server:
  port: 8084
  servlet:
    context-path: '/ead-notification-hex/'

spring:
  application:
    name: ead-notification-service-hex
  datasource:
    url: jdbc:postgresql://localhost:5442/notification-hex
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  rabbitmq:
    addresses: amqps://lastidtg:KwkktjkXOFr0qo96SjJ0nIfvk9jg_aG6@woodpecker.rmq.cloudamqp.com/lastidtg
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  broker:
    exchange:
      notificationCommandExchange: ead.notificationcommand
    queue:
      notificationCommandQueue:
        name: ead.notificationcommand.ms.notification
    key:
      notificationCommandKey: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health