server:
  port: ${PORT}
  servlet:
    context-path: '/ead-course/'

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  application:
    name: ead-course-service
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  rabbitmq:
    addresses: ${CLOUDAMQP_URL}

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEvent:
        name: ead.userevent
      notificationCommand:
        name: ead.notificationcommand
    queue:
      userEvent:
        name: ead.userevent.ms.course
    key:
      notificationCommand:
        name: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health