server:
  port: ${PORT:0}
  servlet:
    context-path: '/ead-authuser/'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/authuser
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  application:
    name: ead-authuser-service
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://lastidtg:KwkktjkXOFr0qo96SjJ0nIfvk9jg_aG6@woodpecker.rmq.cloudamqp.com/lastidtg

logging:
  level:
    com.ead.authuser: INFO
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      userEvent:
        name: ead.userevent

authuser:
  refreshscope:
    name: Eduardo José Souza de Oliveira

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80
  retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s